import Framework from "../../components/framework";
import LContent from "../../components/l-content";

export default function Develop() {
  return (
    <Framework title="Develop | Create Next App" description="Develop | Generated by create next app">
      <LContent top="breadcrumb" breadcrumb="Develop">
        <div className="h-[600px]">Develop</div>
      </LContent>
    </Framework>
  );
}
