import Framework from "../components/framework";
import LContent from "../components/l-content";
import React from "react";

const Home: React.FC = () => {
  return (
    <Framework title="Home | Create Next App" description="Home | Generated by create next app">
      <LContent top="swiper">
        <div className="h-[600px]">Home</div>
        <div>
          <input type="text" name="price" id="price" className="block w-full" placeholder="0.00" />
        </div>
      </LContent>
    </Framework>
  );
};

export default Home;
