import Framework from "../components/framework";
import LContent from "../components/l-content";
import { Button } from "@nextui-org/react";
import Link from "next/link";
import React from "react";

const Home: React.FC = () => {
  return (
    <Framework
      title="Home | Create Next App"
      description="Home | Generated by create next app"
    >
      <LContent top="swiper">
        <div className="h-[600px]">Home</div>
      </LContent>
    </Framework>
  );
};

export default Home;
