import Head from "next/head";
import FrameworkHeader from "./framework-header";
import FrameworkFooter from "./framework-footer";
import React from "react";
import {BackTop} from "@arco-design/web-react";

// 类型约束
interface IProps {
  title?: string;
  description?: string;
  children: any;
}

const Framework: React.FC<IProps> = (props) => {
  return (
    <>
      <Head>
        <title>{props?.title}</title>
        <meta
          name="keywords"
          content="POE Currency, OSRS Gold, Escape From Tarkov Items, Madden Overdrive Coins, FFXIV Gil, Maplestory M Mesos, Steam Level Boost"
        />
        <meta name="description" content={props?.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="framework">
        <FrameworkHeader></FrameworkHeader>
        <div className="framework-container">{props.children}</div>
        <FrameworkFooter></FrameworkFooter>
        <BackTop visibleHeight={300} className="fixed right-[160px] bottom-[160px]">
          <span className="iconfont text-[#666666] hover:text-[#444444] icon-up-square text-[43px]"></span>
        </BackTop>
      </div>
    </>
  );
};

// 定义默认值
Framework.defaultProps = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default Framework;
