import Head from "next/head";
import FrameworkHeader from "./framework-header";
import FrameworkFooter from "./framework-footer";
import React from "react";

// 类型约束
interface IProps {
  title?: string;
  description?: string;
  children: any;
}

const Framework: React.FC<IProps> = (props) => {
  return (
    <>
      <Head>
        <title>{props?.title}</title>
        <meta name="description" content={props?.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="framework">
        <FrameworkHeader></FrameworkHeader>
        <div className="framework-container">{props.children}</div>
        <FrameworkFooter></FrameworkFooter>
      </div>
    </>
  );
};

// 定义默认值
Framework.defaultProps = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default Framework;
