import Framework from "../../components/framework";
import LContent from "../../components/l-content";
import React from "react";
import HomeHotGames from "./hot-games";
import HomeWhyChooseMe from "./why-choose-us";
import HomeCompanyIntroduction from "./company-introduction";
import HomeMethodOfPayment from "./method-of-payment";

const LHome: React.FC = () => {
  return (
    <Framework title="Home | Create Next App" description="Home | Generated by create next app">
      <LContent top="banner">
        <HomeHotGames />
        <HomeWhyChooseMe />
        <div className="w-[1280px] m-auto">
          <h3 className="title">
            <div>Game News</div>
          </h3>
        </div>
        <div className="w-[1280px] m-auto">
          <h3 className="title">
            <div>
              Community ratings <p className="desc">More than 1,000,000 customer reviews on Z2U</p>
            </div>
          </h3>
        </div>
        <div className="w-[1280px] m-auto pb-[64px] flex justify-between">
          <HomeCompanyIntroduction />
          <HomeMethodOfPayment />
        </div>
      </LContent>
    </Framework>
  );
};

export default LHome;
