import Framework from "../../components/framework";
import LContent from "../../components/l-content";
import React from "react";
import HomeHotGames from "./hot-games";
import HomeWhyChooseMe from "./why-choose-us";
import HomeCompanyIntroduction from "./company-introduction";
import HomeMethodOfPayment from "./method-of-payment";
import HomeGamesNews from "./game-news";
import HomeCommunityRatings from "./community-ratings";

const LHome: React.FC = () => {
  return (
    <Framework title="Home | Create Next App" description="Home | Generated by create next app">
      <LContent top="banner">
        <HomeHotGames />
        <HomeWhyChooseMe />
        <HomeGamesNews />
        <HomeCommunityRatings />
        <div className="w-[1280px] m-auto pb-[64px] flex justify-between">
          <HomeCompanyIntroduction />
          <HomeMethodOfPayment />
        </div>
      </LContent>
    </Framework>
  );
};

export default LHome;
